version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data
    command: mongod --wiredTigerCacheSizeGB 1

  keycloak:
    container_name: admin
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8443:8080
    command:
      - start-dev

volumes:
  mongodb_data:
